[package]
name = "anise"
version = "0.1.0"
edition = "2021"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "ANISE provides a toolkit and files for Attitude, Navigation, Instrument, Spacecraft, and Ephemeris data. It's a modern replacement of NAIF SPICE file."
homepage = "https://github.com/anise-toolkit/"
documentation = "https://docs.rs/anise/"
repository = "https://github.com/anise-toolkit/anise.rs"
keywords = ["attitude","navigation","instrument", "spacecraft", "ephemeris"]
categories = ["science", "simulation"]
readme = "README.md"
license = "MPL-2.0"
exclude = ["cspice"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hifitime = {version = "3.5.0", features = ["asn1der"]}
memmap2 = "0.5.7"
crc32fast = "1.3.0"
der = {version = "0.6.0", features = ["derive", "alloc", "real"]}
clap = { version = "4.0.26", features = ["derive"] }
thiserror = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
tabled = "0.10"
const_format = "0.2"
nalgebra = "0.31"
approx = "0.5.1"
zerocopy = "0.6.1"
typenum = "1.15"
rustyline = "10.0.0"
heapless = "0.7.16"

[dev-dependencies]
rust-spice = "0.7.3"
online-statistics = "0.2.6"
parquet = "25.0.0"
arrow = "25.0.0"
criterion = "0.3"
iai = "0.1"
polars = {version = "0.25", features = ["lazy", "parquet"]}

[features]
default = ["std"]
std = []

[profile.bench]
debug = true

[[bench]]
name = "iai_ephemerides"
harness = false

[[bench]]
name = "crit_ephemerides"
harness = false

[[bin]]
name="anise"
features=["std"]

[[bin]]
name="repl"
features=["std"]
